[package]
name = "place-coin"
version = "0.1.0"
edition = "2021"

[lib]
name = "place_coin"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.56"
chrono = "0.4.19"
rayon = "1.5.1"
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
